# Generated by Django 3.2 on 2021-05-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Author_Name', models.CharField(max_length=50)),
                ('Published_Date', models.DateField()),
                ('No_of_pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=60)),
                ('Principal', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=25)),
                ('Last_name', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=60)),
                ('Gender', models.CharField(max_length=10)),
                ('School', models.CharField(max_length=50)),
                ('Books', models.CharField(max_length=30)),
                ('On_Page', models.IntegerField()),
            ],
        ),
    ]
